name: '🐛 Report a bug'
description: Report a reproducible bug or regression.
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting :wave:

        Before filing, please [search](https://github.com/barvian/number-flow/issues?q=is%3Aissue) open & closed issues to see if a similar one exists.

  - type: input
    id: numberflow-version
    attributes:
      label: NumberFlow version
      description: |
        - Please update to the [latest version](https://github.com/barvian/number-flow/releases) before filing to see if your bug has already been fixed.
      placeholder: |
        @number-flow/react@x.x.x
    validations:
      required: true

  - type: input
    id: framework-library-version
    attributes:
      label: Framework version
      # description: Which framework (and version) are you using?
      placeholder: |
        react@x.x.x
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug and the steps to reproduce it
      placeholder: |
        You can drag screenshots or videos into this editor ↓
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: Minimal reproduction (greatly appreciated)
      description: |
        - Links to starter sandboxes can be found in the [site](https://number-flow.barvian.me/) header
        - Tips for creating minimal examples: https://stackoverflow.com/help/mcve
      placeholder: |
        https://codesandbox.io/p/...
    validations:
      required: false

  # - type: textarea
  #   id: screenshots_or_videos
  #   attributes:
  #     label: Screenshots or videos
  #     description: |
  #       For more information on the supported file image/file types and the file size limits, see [GitHub docs](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/attaching-files).
  #     placeholder: |
  #       You can drag your video or image files inside of this editor ↓

  # - type: dropdown
  #   attributes:
  #     options:
  #       - No, because I do not know how
  #       - No, because I do not have time to dig into it
  #       - Maybe, I'll investigate and start debugging
  #       - Yes, I think I know how to fix it and will discuss it in the comments of this issue
  #       - Yes, I am also opening a PR that solves the problem along side this issue
  #     label: Do you intend to try to help solve this bug with your own PR?
  #     description: |
  #       If you think you know the cause of the problem, the fastest way to get it fixed is to suggest a fix, or fix it yourself! However, it is ok if you cannot solve this yourself and are just wanting help.
  # - type: checkboxes
  #   id: agrees-to-terms
  #   attributes:
  #     label: Terms & Code of Conduct
  #     description: By submitting this issue, you agree to follow our Code of Conduct and can verify that you have followed the requirements outlined above to the best of your ability.
  #     options:
  #       - label: I agree to follow this project's Code of Conduct
  #         required: true
  #       - label: I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.
  #         required: true
